# -*- coding: utf-8 -*-
"""dimensionalidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB5AtIW8ngGKhuY158zE4Ua90JWochmY
"""

#reduzir dimensionalidade - tons de cinza + preto e branco
from PIL import Image
import os

#funcao para tratar a imagem com escala de cinza
def escalacinza(colored):
  w, h = colored.size
  img = Image.new("RGB", (w, h))
  for x in range(w):
    for y in range(h):
      r, g, b = colored.getpixel((x,y))
      #pesos das cores para obter tons de cinza - obtidos da weekpedia
      lum = int(0.3*r + 0.59*g + 0.11*b)
      img.putpixel((x,y), (lum, lum, lum))
  return img

#funcao para converter a imagem para preto e branco
def binarizar(cinza):
  limiar = 127  #valor padrão
  w, h = cinza.size
  img = Image.new("RGB", (w, h))
  for x in range(w):
    for y in range(h):
      r, g, b = cinza.getpixel((x, y))
      lum = int((r + g + b) /3)
      if lum > limiar:
        valor_binario = 255
      else:
        valor_binario = 0
      img.putpixel((x, y), (valor_binario, valor_binario, valor_binario))
  return img

img = Image.open('/content/drive/MyDrive/Imagem-bandeira/grafite-prc-maua.jpeg')
#print(img.getpixel((20,20)))
#print(img.getpixel((100,90)))
#print(img.getpixel((150,150)))

img_cinza = escalacinza(img)

img_cinza.save('/content/drive/MyDrive/Imagem-bandeira/grafite-prc-maua-cinza.jpeg')

img_pb = binarizar(img_cinza)

img_pb.save('/content/drive/MyDrive/Imagem-bandeira/grafite-prc-maua-pb.jpeg')

print("fim do programa")